export const links = [
  {
    title: "Digital Transformation",
    icon: "/icons/digital transformation.png",
    link: "/videos/v1.mp4",
    website: "http://www.google.com/search?q=digital+transformation",
  },
  {
    title: "Automation",
    icon: "/icons/automate.png",
    link: "/videos/v1.mp4",
    website: "http://www.google.com/search?q=automation",
  },
  {
    title: "Interaction Analytics",
    icon: "/icons/interaction analytics.png",
    link: "/videos/v1.mp4",
    website: "http://www.google.com/search?q=interaction+analytics",
  },
  {
    title: "Translation Bot",
    icon: "/icons/translation bot.png",
    link: "/videos/v1.mp4",
    website: "http://www.google.com/search?q=translation+bot",
  },
  {
    title: "Vision AI",
    icon: "/icons/vision ai.png",
    link: "/videos/v1.mp4",
    website: "http://www.google.com/search?q=vision+ai",
  },
  {
    title: "Gamification",
    icon: "/icons/gamification.png",
    link: "/videos/v1.mp4",
    website: "http://www.google.com/search?q=gamification",
  },
  {
    title: "Data Analytics",
    icon: "/icons/data analytics.png",
    link: "/videos/v1.mp4",
    website: "http://www.google.com/search?q=data+analytics",
  },
  {
    title: "Digital Transformation",
    icon: "/icons/digital transformation.png",
    link: "/videos/v1.mp4",
    website: "http://www.google.com/search?q=digital+transformation",
  },
  {
    title: "Automation",
    icon: "/icons/automate.png",
    link: "/videos/v1.mp4",
    website: "http://www.google.com/search?q=automation",
  },
  {
    title: "Interaction Analytics",
    icon: "/icons/interaction analytics.png",
    link: "/videos/v1.mp4",
    website: "http://www.google.com/search?q=interaction+analytics",
  },
  {
    title: "Translation Bot",
    icon: "/icons/translation bot.png",
    link: "/videos/v1.mp4",
    website: "http://www.google.com/search?q=translation+bot",
  },
  {
    title: "Vision AI",
    icon: "/icons/vision ai.png",
    link: "/videos/v1.mp4",
    website: "http://www.google.com/search?q=vision+ai",
  },
  {
    title: "Gamification",
    icon: "/icons/gamification.png",
    link: "/videos/v1.mp4",
    website: "http://www.google.com/search?q=gamification",
  },
  {
    title: "Data Analytics",
    icon: "/icons/data analytics.png",
    link: "/videos/v1.mp4",
    website: "http://www.google.com/search?q=data+analytics",
  },
];
